name: files
description: dahliaOS Files.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  animations: ^2.0.7

  collection: ^1.16.0

  ffi: ^2.0.1
  filesize: ^2.0.1
  flutter:
    sdk: flutter

  intl: ^0.18.0
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5

  material_design_icons_flutter: ^6.0.7096 
  mime: ^1.0.3

  path: ^1.8.3
  path_provider: ^2.0.11
  provider: ^6.0.5

  url_launcher: ^6.0.0-nullsafety.6
  windows_path_provider:
    git:
      url: https://github.com/HrX03/windows_path_provider.git
  xdg_directories: ^0.2.0+2

dev_dependencies:
  build_runner: ^2.3.3
  isar_generator: ^3.0.5
  lint: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - lib/assets/locales/
    - lib/assets/icons/
